#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('gmf Installer', '2.0.1');
$app->add(new Gmf\Installer\Console\CreateProjectCommand);
$app->add(new Gmf\Installer\Console\CreatePackageCommand);
$app->run();
